language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'

before_script:
  - phpize
  - ./configure --with-php-config=php-config
  - .travis/run-test.sh make

script:
  - .travis/run-test.sh make test

after_success:

