language: php
sudo: true

php:
  - '5.4'
  - '5.5'
  - '5.6'

before_script:
  - .travis/php-setup.sh
  - phpize
  - ./configure --with-php-config=php-config
  - make

script:
  - yes 'n' | REPORT_EXIT_STATUS=1 make test

after_success:
