language: php
sudo: true

php:
  - '5.4'
  - '5.5'
  - '5.6'

before_script:
  - .travis/php-setup.sh
  - phpize
  - ./configure --with-php-config=php-config
  - make
  - sed -i,.stock -r -e 's/!mail_qa_team\(\$[[:alnum:]_]+,[[:space:]]*\$[[:alnum:]_]+,[[:space:]]*\$[[:alnum:]_]+\)/true/' run-tests.php

script:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 make test

after_success:
